### ISSUE TITLE
Review and update Chapter 1

### ISSUE THREAD

**Issue by Robinlovelace** [geocompx/geocompy#125]
Just looking at Chapter 1, some things are out of date and some things could be improved. On the case!

**Comment by Robinlovelace** [comment]
One thing I note: warnings:

![image](https://github.com/geocompx/geocompy/assets/1825120/b947fc62-2efa-4f6c-8247-41ba64f4a562)

https://py.geocompx.org/01-spatial-data

Also noting #194 by @Nowosad

**Comment by Robinlovelace** [comment]
Fixed by setting `warning: false` in the chapter header, assuming it has no other negative consequences:

![image](https://github.com/geocompx/geocompy/assets/1825120/bfc0a968-1f73-4fb0-9801-40f9a894d42a)

**Comment by Robinlovelace** [comment]
Heads-up @michaeldorman I had a good read over the chapter and it looks great, especially after Jakub's changes. Job done on the review of this tricky intro chapter. Few other thoughts:

- Do we need an earlier 'Introduction' chapter introducing the book, or do we just dive straight in with this as the first chapter (I think either would work, we may want to say more about the advantages of Python and provide context if we keep this as the first chapter)?
- In some places there is lots of output, e.g. shown below, should we not evaluate some of the chunks and in the example below put the many small figures into a single metafigure?

![image](https://github.com/geocompx/geocompy/assets/1825120/7c79b804-dd3d-48d3-ae4a-85d3fd32143a)

These are pretty minor comments, the chapter is good to go IMO!

**Comment by michaeldorman** [comment]
> Heads-up @michaeldorman I had a good read over the chapter and it looks great, especially after Jakub's changes. Job done on the review of this tricky intro chapter. Few other thoughts:
> 
>     * Do we need an earlier 'Introduction' chapter introducing the book, or do we just dive straight in with this as the first chapter (I think either would work, we may want to say more about the advantages of Python and provide context if we keep this as the first chapter)?
> 
>     * In some places there is lots of output, e.g. shown below, should we not evaluate some of the chunks and in the example below put the many small figures into a single metafigure?
> 
> 
> ![image](https://user-images.githubusercontent.com/1825120/275085765-7c79b804-dd3d-48d3-ae4a-85d3fd32143a.png)
> 
> These are pretty minor comments, the chapter is good to go IMO!

1. I think the current structure where we have a preface is good, but starting from the introduction is also possible
2. I like the way that the figure is right next to the code so that the reader can see how specific coordinates are interpreted into a geometry, even if this makes the number of figures very large, but this may be subjective and I'm open to other ideas

**Comment by Nowosad** [comment]
In general, I do not like when there are many figures with minimal text. However, in this situation is fine by me as it allows readers to quickly grasp the idea.

**Comment by Robinlovelace** [comment]
Fine by me too :+1:
