### ISSUE TITLE
Include spherely?

### ISSUE THREAD

**Issue by Robinlovelace** [geocompx/geocompy#147]
Should we include reference to https://github.com/benbovy/spherely and if so how much?

- [ ] Mention of spherely?
- [ ] Description of it?
- [ ] Code examples that use it?

Context: #146 

My current thinking is that we should mention it briefly but that at the time of writing there is "no pre-compiled package available" and the package is still under development, according to the project's README.

Does anyone have any ideas what the roadmap and timelines are? Asking people who I think may be able to help in terms of the package itself @benbovy and it's integration with GeoPandas @martinflies (and many thanks for heads-up on other upcoming changes in this foundational Python package for working with geographic data). Also see https://github.com/geopandas/geopandas/issues/2769 and heads-up @jorisvandenbossche, see you opened that issue 3 days ago so serentipitous timing with our open source book project's evolution!

A question more for book authors: assuming we're aiming to complete the book by end of 2023 what's the rough probability of the package being ready and what's the level of importance of including code examples (I think we should at least mention the existence of this package but not with great conviction and a lot depends on its roadmap I guess)?

Advice and thoughts on this very welcome, it's a bit over my head and way outside my comfort zone but thought it worth asking the community. Great to see these plans evolve and to see R/Python crossover in action as the project makes good use of https://github.com/paleolimbot/s2geography which was split out from the `s2` R package last year: https://github.com/r-spatial/s2/pull/165 amazing work on that @paleolimbot and apologies for tagging everyone on this, hope it's of use/interest and ultimately helpful for the growing community of people using open source software for reproducible geocomputation!

**Comment by michaeldorman** [comment]
We should probably mention `spherely` it at least as a side-note. As for a description and code examples, I agree that it depends on how well developed and stable the package is.

**Comment by benbovy** [comment]
I'd be already very glad if you mention spherely as a side-note here!

There's no detailed roadmap yet, but the basic plan is to replicate shapely's API as much as possible and eventually see how we can integrate it in GeoPandas as an alternative backend.

Short-term (i.e., in the next few weeks), I plan to add a few more features that are available in s2geography (just expose them as Python bindings) and do a pre-release with at least conda(-forge) packages for both s2geography and spherely.

Longer term, it will depend on how much time me and/or other contributors can spend on this project and also if we can get some more funding for its development (which would certainly speed it up). The initial development has been made thanks to a NumFOCUS small development grant for the GeoPandas project. Although I doubt that we'll reach shapely's level of maturity anytime soon for spherely, the API is already well defined and the implementation (s2geography) has been used via the `s2` R package for quite some time, so hopefully we'll be able to provide stable releases without too much effort.

**Comment by Robinlovelace** [comment]
Great stuff Ben, this is really helpful. Good luck with the NumFOCUS plan, that would be great. You could mention this issue as example for demand on that!

**Comment by martinfleis** [comment]
I see that there was an (failed) attempt to tag me here :).

GeoPandas [roadmap](https://geopandas.org/en/stable/about/roadmap.html#beyond-geopandas-1-0) make clarify things in here. Our aim is to release 1.0 within a year from now (early 2024) primarily with shapely parity and shapely 2.0 as the only geometry engine. The implementation of spherely as an engine will depend on the developments in spherely but will not happen before that. So if your book is aimed for end of 2023, I doubt there will be a GeoPandas version with spherely support by then but it is likely that there will be one shortly after (say mid 2024). Not a great timing, I know.

**Comment by Robinlovelace** [comment]
Thanks for the update Martin and aha yes I see I tagged the wrong Martin in the original post! I guess we will not include it but mention and probably link to the roadmap.
