### ISSUE TITLE
GitHub action running for 3+ hours and doesn't complete

### ISSUE THREAD

**Issue by michaeldorman** [geocompx/geocompy#148]
![Screenshot from 2023-01-30 13-56-32](https://user-images.githubusercontent.com/9386655/215470420-76d536e8-a2fb-44fe-8ea1-c37488e54835.png)

**Comment by Robinlovelace** [comment]
Not sure about this. Any ideas @Nowosad? Do we even need this?

**Comment by Nowosad** [comment]
No idea what is the reason of this problem.. It seems that quarto is stuck while rendering `[ 3/10] 02-spatial-data.qmd`...

@Robinlovelace is it needed? Correct me if I am wrong, but this GHA is used to render the html book...

**Comment by Nowosad** [comment]
The issue is related to:

```
Starting python3 kernel...
```

**Comment by Robinlovelace** [comment]
> Correct me if I am wrong, but this GHA is used to render the html book...

Seems right, apologies.

**Comment by Robinlovelace** [comment]
This deploys to gh-pages, we can set-that up to push to Netlify I think if needs be:

https://github.com/geocompx/geocompy/blob/7d6e33a27e330f0f61891ae12523d1679748ab57/.github/workflows/main.yaml#L28

But not sure.

**Comment by Nowosad** [comment]
@Robinlovelace I think that this GHA updates the `gh-pages` branch. Then, Netlify see the change in the branch, and then updates our page.

**Comment by Robinlovelace** [comment]
> Then, Netlify see the change in the branch, and then updates our page.

That happens without the netlify workflow I think.

**Comment by Robinlovelace** [comment]
Also affecting the gh-pages workflow now. 
![image](https://user-images.githubusercontent.com/1825120/215709792-442a8143-9160-4093-9700-bd9c9b02e998.png)

**Comment by michaeldorman** [comment]
I don't know how, but this seems to be fixed :-)

**Comment by Robinlovelace** [comment]
Self fixing issues are the best!
