### ISSUE TITLE
Stop overwriting output/nlcd_4326.tif files

### ISSUE THREAD

**Issue by Robinlovelace** [geocompx/geocompy#157]
I've noticed that each time I build the book it overwrites these files:

```
 rewrite output/nlcd_4326.tif (74%)
 rewrite output/nlcd_4326_2.tif (74%)
```

**Comment by michaeldorman** [comment]
Yes, these files are created for the raster reprojection example:
https://py.geocompx.org/07-reproj.html#sec-reprojecting-raster-geometries
