### ISSUE TITLE
Codespaces Support

### ISSUE THREAD

**Issue by anitagraser** [geocompx/geocompy#173]
What is the current status of the Codespaces support? I can see that building the book works well. The HTML files are created and I can view them in the browsers. But I cannot seem to run the cells in the qmds. Is this expected? Thanks

**Comment by Robinlovelace** [comment]
> What is the current status of the Codespaces support? I can see that building the book works well. The HTML files are created and I can view them in the browsers. But I cannot seem to run the cells in the qmds. Is this expected? Thanks

You should be able to run the cells in the .qmd files. Worked a few months ago. Will give it a spin and report back.

**Comment by Robinlovelace** [comment]
Giving it a go...

![image](https://github.com/geocompx/geocompy/assets/1825120/95abf7ed-c4de-4d12-8e9c-2c2a770bf77f)


Source: https://github.com/codespaces/new?hide_repo_select=true&ref=main&repo=447558863

**Comment by Robinlovelace** [comment]
Confirmed:

**Comment by Robinlovelace** [comment]
Relevant? https://stackoverflow.com/questions/65241321/python-shift-enter-not-working-in-vscode-with-jupyter

**Comment by anitagraser** [comment]
It works on desktop, so this issue seems codespace specific

**Comment by Robinlovelace** [comment]
Interesting... A person who I know has done lots of .devcontainer and Codespaces work is Olivier Benz so, with apologies for tagging you in random issue, any ideas on this @benz0li?

**Comment by benz0li** [comment]
@anitagraser Is the Jupyter extension installed in your Codespace? https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter

ℹ️ Current versions of the Python extension do not install the Jupyter extension alongside by default: https://code.visualstudio.com/updates/v1_78#_python

This may be required to run the cells.

**Comment by anitagraser** [comment]
I see.  Based on the timing, that could indeed be the culprit

**Comment by Robinlovelace** [comment]
:tada: 

![image](https://github.com/geocompx/geocompy/assets/1825120/b14dd972-fa29-47c1-b497-e038ee223fc6)

**Comment by benz0li** [comment]
FYI The book may be reproduced with [`glcr.b-data.ch/jupyterlab/r/qgisprocess`](https://github.com/b-data/jupyterlab-r-docker-stack#jupyterlab-r-docker-stack), which is also available at https://demo.jupyter.b-data.ch.

1. Clone this project.
2. Create a venv within the project:  
    ```bash
    python -m venv .venv
    echo "*" > .venv/.gitignore
    .venv/bin/python -m pip install --upgrade pip
    .venv/bin/python -m pip install -r requirements.txt
    source .venv/bin/activate
    ```
3. Render the book:  
    ```bash
    quarto preview
    ```

---

Cross reference: https://github.com/geocompx/docker/issues/37#issuecomment-1556117717 ff

**Comment by benz0li** [comment]
I have created [[CUDA-enabled] Data Science Development Containers](https://github.com/b-data/data-science-devcontainers).

Dev Container [R qgisprocess](https://github.com/b-data/data-science-devcontainers/blob/main/.devcontainer/r-qgisprocess/devcontainer.json) should work just fine with this repository.

**Comment by Robinlovelace** [comment]
Awesome!
