### ISSUE TITLE
Multi-panel figures

### ISSUE THREAD

**Issue by michaeldorman** [geocompx/geocompy#177]
When creating multi-panel figures, I suggest we use quarto's `layout` and `fig-subcap` options, following @Robinlovelace's example in the mapping chapter:

```{python}
#| label: fig-basic-plot
#| fig-cap: Setting `color` and `edgecolor` in static maps of a vector layer
#| fig-subcap: 
#| - Grey fill
#| - No fill, blue edge
#| - Grey fill, blue edge
#| layout-ncol: 3
nz.plot(color='grey');
nz.plot(color='none', edgecolor='blue');
nz.plot(color='grey', edgecolor='blue');
```

instead of Python's `matplotlib` methods to create panels. This will greatly simplify many of the plotting code sections throughout the book. (In the mapping chapter itself we can still keep an explanation of creating panels using `matplotlib`)

**Comment by Robinlovelace** [comment]
Big win for `quarto` that it can simplify our code like this.

**Comment by michaeldorman** [comment]
> Big win for `quarto` that it can simplify our code like this.

Yes, quarto looks great and fun to work with so far!

**Comment by michaeldorman** [comment]
Done
