### ISSUE TITLE
Use different geographic web services example?

### ISSUE THREAD

**Issue by michaeldorman** [geocompx/geocompy#186]
The ["Geographic web services"](https://r.geocompx.org/read-write#geographic-web-services) example contains `MULTISURFACE` geometries, which works in R:
![Screenshot from 2023-08-13 17-32-48](https://github.com/geocompx/geocompy/assets/9386655/63ed7aba-f094-4d3e-a3af-4691ae5f37d8)
But not in Python:
![Screenshot from 2023-08-13 17-32-19](https://github.com/geocompx/geocompy/assets/9386655/964c08d2-b424-467a-bf1c-301fa626321d)

Should we replace it with a different example that has standard geometry types? Will be happy to hear your thoughts, thanks

**Comment by Nowosad** [comment]
Yep, it would be good to replace it -- in both books. Do you have any suggestions for a data source?

**Comment by michaeldorman** [comment]
> Yep, it would be good to replace it -- in both books. Do you have any suggestions for a data source?

OK 👍
I have little experience with this type of services and don't have an idea at the moment, will try to look for one

**Comment by michaeldorman** [comment]
I don't have any idea for an example yet (and perhaps this section isn't high priority?), so I've commented-out the section for now

**Comment by Nowosad** [comment]
👍🏻
