### ISSUE TITLE
Another example of built-in dataset?

### ISSUE THREAD

**Issue by michaeldorman** [geocompx/geocompy#212]
Since `geopandas.datasets` is [deprecated](https://github.com/geopandas/geopandas/issues/2751) we should probably remove it from the [text](https://py.geocompx.org/07-read-write#sec-geographic-data-packages). 
However, I don't recall any other built-in dataset in a Python package. 
Is there anything that comes to mind as replacement of `gpd.datasets.get_path('naturalearth_lowres')`? Or should we remove the example (perhaps using a built-in dataset from a package isn't very practical anyway, beyond running the examples from package documentation)?

**Comment by Nowosad** [comment]
Hi @michaeldorman -- if there is no tradition in geopython to have geodataset packages -- that is fine to remove it in the book.

**Comment by michaeldorman** [comment]
Sure, this makes sense to me
https://github.com/geocompx/geocompy/commit/56cd43eb049cacb7c6fb64df01fe98bf0df4cf71
