### ISSUE TITLE
Switch geocoding from `osmnx` to `geopandas`

### ISSUE THREAD

**Issue by michaeldorman** [geocompx/geocompy#214]
Following @Nowosad comments and on second thought, I suggest not using `osmnx` for geocoding, here:
https://py.geocompx.org/07-read-write#sec-geographic-data-packages
since `osmnx` doesn't have a built-in way to deal with "no results". 
Instead, we can use `geopandas` as shown here:
https://geopandas.org/en/stable/docs/user_guide/geocoding.html#geocoding
Will be happy to hear any thoughts or other suggestions, thanks!

**Comment by anitagraser** [comment]
Looks great. Definitely worth a try

**Comment by michaeldorman** [comment]
Done
https://github.com/geocompx/geocompy/commit/1fa5a334c1dccd32602737f6743cdb710ced54f5
