### ISSUE TITLE
Geometric intersections section removal

### ISSUE THREAD

**Issue by Nowosad** [geocompx/geocompy#219]
> that's correct, the only difference is that here the cropping geometry comes from another raster, however in 'rasterio' there is no distinct way to crop using a raster, so indeed most of the workflow is the same. I agree this section mostly repeats the same material, it's fine with me to remove it 

I would suggest to remove this section (and related cross-references to it) -- it is redundant

**Comment by michaeldorman** [comment]
Done, thanks 
https://github.com/geocompx/geocompy/commit/aed81a9d2928faa2698602d8cec641a3b4af387a
