### ISSUE TITLE
Consider adding pyogrio example

### ISSUE THREAD

**Issue by Nowosad** [geocompx/geocompy#220]
> "**geopandas** uses GDAL to read and write data, via **fiona** (the [default](https://github.com/geopandas/geopandas/issues/2217)) or **pyogrio** packages (a recently developed alternative to **fiona**, which will become the default in the future, see [note](https://geopandas.org/en/stable/docs/user_guide/io.html) in "Reading and writing files" tutorial)."

Currently, we show some **fiona** examples (https://py.geocompx.org/07-read-write) -- however, shouldn't we replace them with **pyogrio** examples (more future-proof)?

**Comment by michaeldorman** [comment]
We did this as part of the review comments, for example here:
https://py.geocompx.org/07-read-write#sec-input-vector
