### ISSUE TITLE
'shapely' access methods

### ISSUE THREAD

**Issue by Nowosad** [geocompx/geocompy#221]
> now added a reference to the place where '.geoms' is mentioned, but it's not really explained; there is no comprehensive overview of 'shapely' access methods in the book at the moment. we could add a section about that (e.g., https://geobgu.xyz/py/07-shapely.html#geometry-coordinates), will be happy to hear what you think

How about you add a paragraph (+table?) in https://py.geocompx.org/01-spatial-data#sec-geometries with 'shapely' access methods?

**Comment by michaeldorman** [comment]
IMHO this may be beyond the scope of the book; at the end of the above-mentioned paragraph we do list the access methods (`.coords`, `.geoms`, `.exterior`, `.interiors`). However, explaining how they work will take up some space (basically [this](https://geobgu.xyz/py/07-shapely.html#geometry-coordinates) entire section) and will be irrelevant to most readers. I therefore suggest we leave the list as is. To those few readers for whom this is relevant can further explore the methods (also, method names are somewhat self-explanatory)

**Comment by Robinlovelace** [comment]
Sounds like a good plan Michael, closing for now..
