### ISSUE TITLE
Improve "Code and sample data" section

### ISSUE THREAD

**Issue by Nowosad** [geocompx/geocompy#222]
https://py.geocompx.org/preface#code-and-sample-data

1. It only lists .ipynb and \data files. Many chapters also rely on the \output files (created in Chapter 1), however, I assume that some reader will only try to run some chapters. Maybe we could make copies of some files from \output to \data? Or you have some better idea?
2. "landsat.tif" is not in the \data folder of the repo (maybe some others are also missing)
3. Do we even use some of the files listed (e.g., yorkshire.json)? 
4. Can you explain me how the ipynb files are created? Maybe I could modify our GitHub action to make them automatically...

**Comment by michaeldorman** [comment]
Thanks for noticing these issues @Nowosad , I'll check it out.

Before that, there's something I don't understand - the contents of my local `data` directory (please see below) doesn't match the one on GitHub. For example, I do have `landsat.tif` locally. Also, `data` is not in `.gitignore`. I wonder what other reason could there be for the difference, and how can I fix it so that I'm in sync with GitHub. I was thinking that "commit all" should do it, but apparently not. (@Robinlovelace, @anitagraser, maybe you also have an idea?) Thanks!

```sh
├── absolute_v5.nc
├── aut.tif
├── ch.tif
├── coffee_data.csv
├── cycle_hire.gpkg
├── cycle_hire_osm.gpkg
├── cycle_hire_xy.csv
├── dem.tif
├── landsat.tif
├── nlcd.tif
├── nz_elev.tif
├── nz.gpkg
├── nz_height.gpkg
├── seine.gpkg
├── srtm.tif
├── us_states.gpkg
├── world.gpkg
├── world_wkt.csv
├── yorkshire.json
├── zion.gpkg
└── zion_points.gpkg
```

**Comment by michaeldorman** [comment]
1. You're right, thanks! Now corrected in the text (https://github.com/geocompx/geocompy/commit/d0eb98107dde873b2b385132bbcbe8d67ca1d205)

**Comment by michaeldorman** [comment]
2. `landsat.tif` was in `.gitignore`, I now removed the entry from there. I checked and no other files are missing

**Comment by michaeldorman** [comment]
3. Right, thanks! Now removed `yorkshire.json`, there are no other unnecessary files as far as I checked

**Comment by michaeldorman** [comment]
4. The `.ipynb` files are created using:
```sh
for i in *.qmd; do
  quarto convert $i
done
```
(https://github.com/geocompx/geocompy/blob/main/convert.sh)
It's a good idea if this can be automatic, thanks

**Comment by Nowosad** [comment]
@michaeldorman -- see https://github.com/geocompx/geocompy/tree/geocompy.

I think I was able to create a GitHub action that creates ipynb files and move them (and data folder) to a new branch. See https://github.com/geocompx/geocompy/blob/main/.github/workflows/prep-book-package.yml.

This GitHub action only starts when your commit message contains "update book package"

**Comment by Nowosad** [comment]
The above approach allows us to create GitHub releases (from the geocompy branch): see https://github.com/geocompx/geocompy/releases/tag/0.2. 

@michaeldorman would you be able to update the data/code instructions in the book?

**Comment by michaeldorman** [comment]
Hi @Nowosad ,looks great, thanks! Perhaps the release can also contain the `output` directory? (according to note (1) in the first comment in this thread)

**Comment by Nowosad** [comment]
See it now: https://github.com/geocompx/geocompy/tree/geocompy

Let me know if there is something still missing. If not -- feel free to create a new release.

**Comment by michaeldorman** [comment]
As far as I can tell this is solved, so closing, thanks @Nowosad 🙏
