### ISSUE TITLE
First sentence in preface seems to be missing a few tokens

### ISSUE THREAD

**Issue by chrisjkuch** [geocompx/geocompy#223]
From the first sentence in the [Preface](https://py.geocompx.org/preface):

> Geocomputation with Python (geocompy) is motivated by the need for an introductory, yet rigorous and up-to-date, **resource geographic data** with the most popular programming language in the world.

I think this should read something like "resource for working with geographic data" since otherwise it's not quite a complete sentence.

**Comment by Robinlovelace** [comment]
Thanks @chrisjkuch, fixed in the commit above I think. Any other comments/suggestions welcome!
