### ISSUE TITLE
Next page button is broken

### ISSUE THREAD

**Issue by jeromemaiquez** [geocompx/geocompy#224]
Hi! First off, I want to commend all of you guys for this project 🤩

Just noticed that the next page button isn't working from the Preface page onwards. The link doesn't work and beside it appears the following text: `' class='pagination-link' href='/01-spatial-data'>`.

The button for going to the previous page seems to be working fine.

Here is a screenshot for easier reference:
![image](https://github.com/geocompx/geocompy/assets/146398026/a74fb93f-583f-498c-99f8-dab02b7fff06)

Thanks, and cheers once again!

**Comment by Nowosad** [comment]
Thanks @jeromemaiquez. I looked online and this seems to be an upstream issue in Quarto (which is used to build the book). See https://github.com/quarto-dev/quarto-cli/issues/8555

**Comment by michaeldorman** [comment]
Thanks @Nowosad !
