### ISSUE TITLE
Section and figure links not rendered

### ISSUE THREAD

**Issue by michaeldorman** [geocompx/geocompy#228]
For example:
https://py.geocompx.org/03-spatial-operations#sec-spatial-subsetting-vector
![image](https://github.com/geocompx/geocompy/assets/9386655/51ddabd9-09d0-4d32-a9fe-5d0349dd0068)

**Comment by Nowosad** [comment]
It should be fixed now (I needed to update Requirements and the docker file)

**Comment by Nowosad** [comment]
FYI: this happens when there are some errors while book rendering (e.g., missing required packages)

**Comment by michaeldorman** [comment]
> FYI: this happens when there are some errors while book rendering (e.g., missing required packages)

I see, thanks @Nowosad
