### ISSUE TITLE
Switch to `geopandas` version `>=1.0.0`

### ISSUE THREAD

**Issue by michaeldorman** [geocompx/geocompy#229]
Following our discussion, there are some changes in the book code that require `geopandas` [pre-release](https://martinfleischmann.net/geopandas-1.0-is-coming.-what-will-change/) version `1.0.0`. 
I tried `geopandas>=1.0.0-alpha1` in `requirements.txt` (following [this](https://stackoverflow.com/questions/38762416/how-to-specify-python-requirements-by-allowing-prereleases)), but the book is still being built with `geopandas` `0.14.0`. Will appreciate any help with this, thanks

**Comment by Nowosad** [comment]
Try it now and let me know, @michaeldorman

**Comment by michaeldorman** [comment]
Works now, thanks @Nowosad !
