### ISSUE TITLE
URLs to function docs?

### ISSUE THREAD

**Issue by michaeldorman** [geocompx/geocompy#232]
Should we have links to function docs, in the text where it's first mentioned? Right now this is inconsistent

**Comment by Robinlovelace** [comment]
Pros and cons:

- Pro: more useful
- Con: time and possible maintenance burden if URLs change

Given that many people will read the book in non-sequential order I'm not sure there's much benefit of only linking on first mention. So tentatively suggest no, but no objections.

**Comment by michaeldorman** [comment]
I agree, so it's on the to-do list to remove the existing links to docs (which we have for some of the functions where they are first mentioned)

**Comment by Nowosad** [comment]
@michaeldorman close?

**Comment by michaeldorman** [comment]
> @michaeldorman close?

Yes, all links were already removed unless we missed something. Thanks
