### ISSUE TITLE
Duplicated table of contents entries in the TOC of PDF

### ISSUE THREAD

**Issue by michaeldorman** [geocompx/geocompy#237]
![Screenshot from 2024-07-09 11-13-14](https://github.com/geocompx/geocompy/assets/9386655/bc9fe136-c043-4407-987e-3ee033750d0b)

**Comment by Nowosad** [comment]
@michaeldorman I think these is due to some inconsistency between crc press latex style and rmarkdown/quarto. I also think this issue can be easily fixed in the .tex file by the publishers' technical team (it requires removing a line or two there).

**Comment by michaeldorman** [comment]
Thanks @Nowosad , I agree, perhaps let's just keep the issue open for the record until this is fixed
