### ISSUE TITLE
Figures is distorted in the PDF

### ISSUE THREAD

**Issue by michaeldorman** [geocompx/geocompy#239]
Figure 1.24 (below)
Figure 3.17
![image](https://github.com/geocompx/geocompy/assets/9386655/c869a29b-4ef7-4a88-b284-8e7fca0ac4d9)

**Comment by Robinlovelace** [comment]
That is quite some distortion! Could be worth saving the file as a .png and including the graphics? I wonder if it's trying to show the vectorised version..

**Comment by Nowosad** [comment]
@michaeldorman both figures look good in the version rendered on my local machine (that I've sent to you today)
