### ISSUE TITLE
Line height and space around code blocks is small in PDF (compared to Jakub's setup)

### ISSUE THREAD

**Issue by michaeldorman** [geocompx/geocompy#240]
This is what I get:
![Screenshot from 2024-07-09 16-53-14](https://github.com/geocompx/geocompy/assets/9386655/1599cf6c-a897-44a7-9b0b-34b0ec082cb7)

This is from @Nowosad 's PDF:
![Screenshot from 2024-07-09 16-53-16](https://github.com/geocompx/geocompy/assets/9386655/74f3d4ba-25c7-4096-96bf-4a81ba670840)

**Comment by michaeldorman** [comment]
@Nowosad Do you have an idea what could be different in my setup causing the reduced line space? Thanks

**Comment by Robinlovelace** [comment]
I just generated the pdf and the vertical distance between prose and code chunks is the same a @michaeldorman's:

![image](https://github.com/user-attachments/assets/232d9ab2-d01e-449d-8bb2-0bb046873c00)

**Comment by Robinlovelace** [comment]
LaTeX versions?

Mine seems quite recent:

```
pdfTeX 3.141592653-2.6-1.40.26 (TeX Live 2024)
kpathsea version 6.4.0
Copyright 2024 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.43; using libpng 1.6.43
Compiled with zlib 1.3.1; using zlib 1.3.1
Compiled with xpdf version 4.04

```

**Comment by Robinlovelace** [comment]
```
➜  geocompr git:(main) ✗ xelatex --version
XeTeX 3.141592653-2.6-0.999996 (TeX Live 2024)
kpathsea version 6.4.0
Copyright 2024 SIL International, Jonathan Kew and Khaled Hosny.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the XeTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the XeTeX source.
Primary author of XeTeX: Jonathan Kew.
Compiled with ICU version 74.2; using 74.2
Compiled with zlib version 1.3.1; using 1.3.1
Compiled with FreeType2 version 2.13.2; using 2.13.2
Compiled with Graphite2 version 1.3.14; using 1.3.14
Compiled with HarfBuzz version 8.3.0; using 8.3.0
Compiled with libpng version 1.6.43; using 1.6.43
Compiled with pplib version v2.2
Compiled with fontconfig version 2.13.0; using 2.13.1

```

**Comment by michaeldorman** [comment]
I've just installed all software from scratch (Ubuntu update to 24.04 went wrong...), using tinytex according to the instructions on quarto website, and still have the issue

https://quarto.org/docs/output-formats/pdf-engine.html#installing-tex

**Comment by Robinlovelace** [comment]
Is it an issue though? The reduced linespaces look OK to me. @Nowosad do you have any suggestions?

**Comment by michaeldorman** [comment]
> Is it an issue though? The reduced linespaces look OK to me. @Nowosad do you have any suggestions?

IMHO @Nowosad 's version looks much better and the way that it should be, so I suggest that's what we'll submit.
At least I can render the PDF to review the text one last time... And regardless it's interesting what might be the difference between our setups

**Comment by Nowosad** [comment]
I will try to find some time this afternoon to find the answer. (At the same time, @michaeldorman remember, that we also provide .tex to the publisher and the .tex file is actually then processed by them and printed. Thus, we do not need to worry too much about it, imo)

**Comment by michaeldorman** [comment]
> I will try to find some time this afternoon to find the answer. (At the same time, @michaeldorman remember, that we also provide .tex to the publisher and the .tex file is actually then processed by them and printed. Thus, we do not need to worry too much about it, imo)

Sure, no worries. It's was just interesting for general information, if you have an idea, no need to investigate it for the purposes of the book

**Comment by michaeldorman** [comment]
> > I will try to find some time this afternoon to find the answer. (At the same time, @michaeldorman remember, that we also provide .tex to the publisher and the .tex file is actually then processed by them and printed. Thus, we do not need to worry too much about it, imo)
> 
> Sure, no worries. It was just interesting for general information, if you have an idea, no need to investigate it for the purposes of the book

**Comment by Robinlovelace** [comment]
Let's submit the book. It's close between geocompy v1 and geocompr v2 now!

**Comment by michaeldorman** [comment]
> Let's submit the book. It's close between geocompy v1 and geocompr v2 now!

Sure, I'd just like to read the PDF one more time, it'll take time so I suggest we submit some time closer to the deadline (Oct 16th). When done I'll ask Jakub to render the more optimal PDF and then we can submit if that's OK. Thanks 🙏

**Comment by Robinlovelace** [comment]
That sounds great to me Michael, worth getting it right.

**Comment by Nowosad** [comment]
![image](https://github.com/user-attachments/assets/81273abc-a4da-467d-a689-e67dbd2b6d63)

This is the same page using a new laptop (Fedora Linux; I still have the old one, so we can check its output next week)

**Comment by Robinlovelace** [comment]
Latest thought: Quarto version.

**Comment by Robinlovelace** [comment]
Which versions are you on @michaeldorman and @Nowosad ?

```
quarto check
Quarto 1.5.57
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.57
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/robin/.TinyTeX/bin/x86_64-linux
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12
      Path: /usr/bin/python3
      Jupyter: 5.3.0
      Kernels: python3, geocompy, julia-1.10, mojo-jupyter-kernel, mojo-max-jupyter-kernel

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.4.1
      Path: /usr/lib/R
      LibPaths:
        - /home/robin/R/x86_64-pc-linux-gnu-library/4.4
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: 1.48
      rmarkdown: 2.28

[✓] Checking Knitr engine render......OK

```

**Comment by michaeldorman** [comment]
```sh
Quarto 1.5.57
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.57
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.10
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/michael/.TinyTeX/bin/x86_64-linux
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.3
      Path: /usr/bin/python3
      Jupyter: 5.3.2
      Kernels: venv

(|) Checking Jupyter engine render....Traceback (most recent call last):
  File "/opt/quarto/share/jupyter/jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "/opt/quarto/share/jupyter/notebook.py", line 19, in <module>
    from nbclient import NotebookClient
ModuleNotFoundError: No module named 'nbclient'
[✓] Checking Jupyter engine render....OK
```

**Comment by michaeldorman** [comment]
> ![image](https://private-user-images.githubusercontent.com/3457131/374231677-81273abc-a4da-467d-a689-e67dbd2b6d63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNzIwMjksIm5iZiI6MTcyODM3MTcyOSwicGF0aCI6Ii8zNDU3MTMxLzM3NDIzMTY3Ny04MTI3M2FiYy1hNGRhLTQ2N2QtYTY4OS1lNjdkYmQyYjZkNjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDhUMDcxNTI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2EyNzU4YTczNzI4ZTIzYzhkNDgxYzc1NjNhNmNjYmJlODViZDgwMmViYzlmZTgwYjZkMThmYzRlMWRkNGNlNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.GPlYNwKRKsK0GyN4bbcyTCH2ga29_DCxOpDycK_gM_E)
> 
> This is the same page using a new laptop (Fedora Linux; I still have the old one, so we can check its output next week)

Thanks! Interesting...

**Comment by Nowosad** [comment]
```
Quarto 1.6.10
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.6.10
      Path: /home/jn/opt/quarto-1.6.10/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: 869685

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/jn/.TinyTeX/bin/x86_64-linux
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.6
      Path: /usr/bin/python3
      Jupyter: 5.7.2
      Kernels: python3, julia-1.11

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.4.1
      Path: /usr/lib64/R
      LibPaths:
        - /home/jn/R/x86_64-redhat-linux-gnu-library/4.4
        - /usr/lib64/R/library
        - /usr/share/R/library
      knitr: 1.48
      rmarkdown: 2.28

[✓] Checking Knitr engine render......OK
```
