### ISSUE TITLE
Rendering fails

### ISSUE THREAD

**Issue by michaeldorman** [geocompx/geocompy#241]
Book rendering fails:

![Screenshot from 2024-08-06 16-45-48](https://github.com/user-attachments/assets/b66dd542-d635-4910-b993-496f5fe21d4c)

Also, links to sections are not being rendered:

![image](https://github.com/user-attachments/assets/0ae3d330-5548-49ce-ab5e-fd307ac7ec9b)

**Comment by Robinlovelace** [comment]
Will take a look...

**Comment by michaeldorman** [comment]
> Will take a look...

Thanks @Robinlovelace  🙏

**Comment by Robinlovelace** [comment]
It's due to `osmnx` vs `geopandas` incompatibility: 

```
The conflict is caused by:
    The user requested geopandas>=1.0.0-alpha1
    osmnx 1.9.4 depends on geopandas<0.15 and >=0.12
```

Source: https://github.com/geocompx/geocompy/actions/runs/10267705788/job/28408888233#step:4:129

**Comment by Robinlovelace** [comment]
On the case, with upgrade osmnx version:

**Comment by Robinlovelace** [comment]
https://github.com/geocompx/geocompy/blob/3b0f9ae9969757c1f9329c8340f4676e05ff70c5/environment.yml#L29

Oh, it's not pinned...
