### ISSUE TITLE
Section links fail

### ISSUE THREAD

**Issue by Robinlovelace** [geocompx/geocompy#243]
Links to sections are not being rendered:

> 
> ![image](https://private-user-images.githubusercontent.com/9386655/355474016-0ae3d330-5548-49ce-ab5e-fd307ac7ec9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NzM0ODYsIm5iZiI6MTcyMjk3MzE4NiwicGF0aCI6Ii85Mzg2NjU1LzM1NTQ3NDAxNi0wYWUzZDMzMC01NTQ4LTQ5Y2UtYWI1ZS1mZDMwN2FjN2VjOWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDZUMTkzOTQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmM2YmI1M2I2Y2JlZmJiNTRkNjMzODNlYTNmOThiMTM1YzhlZWJlOTc3NTgzODFlMTA3OTJlMDc1MWE3NjRhYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.76QN_zWgrBDcdGMgKr7IDbj4yNWzygAqlV-zMToedMw)

Split-out from #241 

Also in Chapter 1:

> The vector data model ([sec-vector-data](https://py.geocompx.org/01-spatial-data#sec-vector-data))

 https://py.geocompx.org/01-spatial-data

**Comment by Robinlovelace** [comment]
Cannot reproduce this issue locally as shown below. Quarto version issue?

![image](https://github.com/user-attachments/assets/2ca6eb81-d32d-47f0-a9fd-4cf3f0a953aa)

To do that:

```
quarto --version 1.5.47
quarto preview
```

**Comment by Robinlovelace** [comment]
Will try

```
docker run -it ghcr.io/geocompx/docker:python /bin/bash
```

to debug...

**Comment by Robinlovelace** [comment]
The container has a different version:

```
➜  ~ docker run -it ghcr.io/geocompx/docker:python /bin/bash
root@32d56fcb7ad0:/# quarto --version
1.5.41
```

**Comment by Robinlovelace** [comment]
Will try installing that version to debug locally...

**Comment by Robinlovelace** [comment]
Looks like another quarto regression to me.

**Comment by Robinlovelace** [comment]
Latest version:

```
root@96152b486388:/workspaces/geocompy# quarto --version
1.5.54
```

**Comment by Robinlovelace** [comment]
Cannot reproduce in devcontainer, I'm confused... Any ideas @Nowosad ?

![image](https://github.com/user-attachments/assets/bbc1fe84-7f6e-4143-a2cf-8c8090540f42)

**Comment by Robinlovelace** [comment]
There is something unexpected in the workflow logs:

```

pandoc 
  to: latex
  output-file: index.tex
  standalone: true
  toc: true
  number-sections: true
  top-level-division: chapter
  pdf-engine: xelatex
  variables:
    graphics: true
    tables: true
  default-image-extension: pdf
  
metadata
  crossref:
    chapters: true
  documentclass: krantz
  papersize: letter
  block-headings: true
  jupyter: python3
  bibliography:
    - geocompr.bib
  monofont: Source Code Pro
  monofontoptions:
    - Scale=0.7
  description-meta: |
    This book will teach you how to work with geographic data in Python.
    It's a short and practical open source book in which you'll
    develop and use geocomputation to solve practical
    problems and lay the foundations for advanced geospatial applications.
  title: Geocomputation with Python
  author: 'Michael Dorman, Anita Graser, Jakub Nowosad, Robin Lovelace'
  description: |
    An introductory resource for working with geographic data in Python
  
FATAL (/opt/quarto/share/filters/main.lua:7217) An error occurred:
Could not convert a SVG to a PDF for output. Please ensure that rsvg-convert is available on the path.
Error running filter /opt/quarto/share/filters/main.lua:
/opt/quarto/share/filters/main.lua:2639: attempt to call a nil value (global 'crash_with_stack_trace')
stack traceback:
	/opt/quarto/share/filters/main.lua:2218: in function 'fail'
```

Source: https://github.com/geocompx/geocompy/actions/runs/10272870283/job/28426047661#step:4:1295

**Comment by Robinlovelace** [comment]
Fixed in https://github.com/geocompx/geocompy/commit/cb47eccda5977974a2ac4d5764f00fcc18d342ce

Note @Nowosad: let's keep the pdf bits commented-out until we need them.

**Comment by Robinlovelace** [comment]
Demo: https://py.geocompx.org/01-spatial-data#sec-vector-data

**Comment by michaeldorman** [comment]
Great, thanks @Robinlovelace ! 🙏 
I guess if there is incompatibility between the HTML and PDF rendering we can switch to PDF setting when needed (which should be rare). At the moment only @jakub could accomplish the PDF rendering
