### ISSUE TITLE
Import rasterio plot missing

### ISSUE THREAD

**Issue by anitagraser** [geocompx/geocompy#255]
This issue was reported to me on Linkedin:

> I was working through your book Geocomputation with Python and there is one section where you use rasterio.plot.show() and that needs to be imported as from rasterio import plot before it works.

**Comment by michaeldorman** [comment]
Thanks @anitagraser , can you please ask them to be more specific? I looked through the chapters and IMHO we're using `import rasterio.plot`, and then `rasterio.plot.show()`, throughout the book, so couldn't find an issue with it

**Comment by Robinlovelace** [comment]
I suspect it was a question of *where* `rasterio import` was and where it was expected. Given the lack for additional info let's close for now, we can reopen if more information emerges from the ether.
