### ISSUE TITLE
Reduce width of some figures in PDF

### ISSUE THREAD

**Issue by michaeldorman** [geocompx/geocompy#263]
The `#| out-width: X%` command seems to have no effect on the PDF, so some of the figures come out too big. For example, Fig. 1.21. I guess this requires trial and error with rendering the PDF (@Nowosad), or the publisher can do it? 

![Screenshot from 2024-10-05 14-18-15](https://github.com/user-attachments/assets/4b54db37-6b02-4a60-a196-39c421351467)
![Screenshot from 2024-10-05 14-16-52](https://github.com/user-attachments/assets/70a08c24-86fd-4b28-bd4f-8b12bb3ac53f)

**Comment by Nowosad** [comment]
"`out-*` options are knitr only options"; thus, we can use `fig-width` instead

**Comment by michaeldorman** [comment]
> "`out-*` options are knitr only options"; thus, we can use `fig-width` instead

I Just tried `fig-width`, seems like it has no effect either

**Comment by Nowosad** [comment]
True. This seems to explain the issue: https://github.com/quarto-dev/quarto-cli/issues/3155:

> Ok, this turns out to be a known issue. The problem is that we don't have a mechanism for communicating these at a cell level. In jupyter engines, fig-width and fig-height only work as engine defaults (on the global yaml metadata).

**Comment by Nowosad** [comment]
Also see https://quarto.org/docs/computations/execution-options.html#figure-options

**Comment by birnstiel** [comment]
Is there any workaround for this? I tried putting `fig-width: 3` in the pdf or html settings and in the global settings, but still my figures are an entire PDF page high and run over on the right side of the PDF.
