### ISSUE TITLE
Reference of `tmap` book

### ISSUE THREAD

**Issue by michaeldorman** [geocompx/geocompy#264]
I'm not sure how to solve this request (from ch08), please check it out @Nowosad 

![image](https://github.com/user-attachments/assets/c1baa882-9298-4679-aa65-1b056c8822b5)

**Comment by Nowosad** [comment]
@michaeldorman I think the best you can do is to add an url and maybe a (in progress) comment

**Comment by michaeldorman** [comment]
I'll try that, thanks
