### ISSUE TITLE
Switch to Python 3.11

### ISSUE THREAD

**Issue by Robinlovelace** [geocompx/geocompy#53]
It seems this will be a major release with lots of performance enhancements: https://docs.python.org/3.11/whatsnew/3.11.html

Problem is, seems that `conda` will lag behind the official release: https://github.com/conda-forge/conda-forge.github.io/issues/1629

According to the [release schedule](https://peps.python.org/pep-0664/) the full 3.11 release will be published around October 2022 so we don't need to do anything atm, just opening this up here so we're ready and to get feedback on that. From then it seems that Python 3.11 will be supported for the next 5 years so I suggest we pin to that version for stability when it's ready and stable, including on `conda`. Sound reasonable @anitagraser ?

**Comment by anitagraser** [comment]
There's no need to hurry to 3.11 imho but - once its on conda - we should keep an eye on the support in our spatial libraries

**Comment by Nowosad** [comment]
We are already using 3.11: https://github.com/geocompx/docker/blob/master/python/Dockerfile
