### ISSUE TITLE
Domain name

### ISSUE THREAD

**Issue by Robinlovelace** [geocompx/geocompy#69]
Currently the book is hosted in 2 places:

Directly from GitHub pages: http://geocompr.github.io/py

Random netlify deploy: https://vocal-longma-0d407b.netlify.app/ #68 

We can continue with just the former no problem as the default. Advantage: simplicity.

Advantage of custom domain hosted by Netlify:

- Netlify deploys do not add anything to the commit history or repo size keeping it clean
- Potential advantage in terms of discoverability with custom domain

This is linked to a broader question about where to host all 'geocompr' repos, we could get economies of scale by hosting many of them on the same site:

- Geocomputation with R, deployed from gh-pages branch via Netlify to https://geocompr.robinlovelace.net/ default plan is to continue to host it there but am open to moving it at some point, e.g. to geocomp.xyz/r
- Associated book website, blog and solutions
- Spanish translation
- French translation
- Japanese translation
- ... translation in another human language
- translation into another computer language e.g. JavaScript or Rust

All this and more could live on a custom domain. That may take some setting up. Options

geocomp.xyz suggested by Jakub

geowith.com suggested by me (over a coffee :coffee: ) thinking that r.geowith.com and py.geowith.com, as in geo(computation) with r/py/.../ could be good and then have r.geowith.com/en etc as consistent sites. 

This would be a big operation and not to be taken lightly. Simple is good. So the default is to keep it as is for now with the silent Netlify deploys as an experimental backup but thought I'd dump thoughts on this hear while fresh in my head (have discussed broadly with Jakub who suggested a dedicated URL partly as geocompr does not fit so well with the Pythonic nature of this project already but keen to hear what others think).

**Comment by michaeldorman** [comment]
All of the options sound good to me! Don't have a specific preference.

**Comment by Nowosad** [comment]
(FYI: I bought the geocomp.xyz domain a week ago; we do not need to use it, but we have it;))

**Comment by Robinlovelace** [comment]
As a stop-gap and fall-back option we could can rename the org to geocomp x. thoughts welcome, esp. @Nowosad, also see Discord : )

**Comment by Nowosad** [comment]
See https://github.com/geocompr/geocompr.github.io/issues/21

**Comment by Nowosad** [comment]
https://py.geocomp.xyz/

**Comment by Nowosad** [comment]
Also see https://github.com/geocompr/geocompr.github.io/discussions/23

**Comment by Nowosad** [comment]
https://py.geocompx.org/
