### ISSUE TITLE
Add text around new content for chapter 9

### ISSUE THREAD

**Issue by Robinlovelace** [geocompx/geocompy#74]
Following recently merged #57 we should add some text to describe the code at the very least. I'm up for taking a first look at this so assigning myself but may ask for input @anisotropi4 so any comments from you or anyone welcome. The vis. chapter is in an early state of development so may be worth adding basic content before this more advances stuff but we can add a link and a brief description at the very least.

**Comment by anisotropi4** [comment]
Do you want me to have a go at this as I am becoming more familiar with the house style?

**Comment by Robinlovelace** [comment]
> Do you want me to have a go at this as I am becoming more familiar with the house style?

Yes please if you find time :+1:

**Comment by anisotropi4** [comment]
This is a first draft at a the NaPTAN example. It is missing the precision code and the `index.html` creation.

**Comment by Robinlovelace** [comment]
Looks great to me: https://github.com/geocompr/py/pull/80#pullrequestreview-1029487891 Any comments from others v. welcome. Many thanks!

**Comment by michaeldorman** [comment]
Looks good to me! Thanks

**Comment by Robinlovelace** [comment]
> I was going to add the other two examples from "pitching ideas". Due to data size I will need to limit this to, say, Yorkshire.

Sounds good to me :+1: just need to figure out how to figure out great reproducible examples into the book

**Comment by Nowosad** [comment]
Feel free to reopen if needed.
