### ISSUE TITLE
Switch installation instructions to mamba

### ISSUE THREAD

**Issue by Robinlovelace** [geocompx/geocompy#81]
Which just seems nicer. Example below...

![Peek 2022-08-22 09-09](https://user-images.githubusercontent.com/1825120/185872343-c80f1e40-efbc-48b0-aecc-2dcdc02e1426.gif)

**Comment by Nowosad** [comment]
Currently, we suggest micromamba (which works great, btw) -- https://github.com/geocompx/geocompy#install-dependencies-with-a-package-manager
