### ISSUE TITLE
Binder is failing

### ISSUE THREAD

**Issue by Robinlovelace** [geocompx/geocompy#84]
Not sure why but this does not give me the Jupyter environment I would expect: https://mybinder.org/v2/gh/geocompr/py/main?urlpath=lab/tree/ipynb

**Comment by Robinlovelace** [comment]
If anyone knows what this means, let me know!

```
Picked Git content provider.
Cloning into '/tmp/repo2dockert9jxydil'...
HEAD is now at de8262e Distances section.
Using DockerBuildPack builder
Step 1/6 : FROM continuumio/miniconda3
 ---> ce7d119281a1e...
Step 2/6 : RUN wget https://github.com/geocompr/py/raw/main/environment.yml
 ---> Running in fb80020bc128
--2022-08-25 17:38:43--  https://github.com/geocompr/py/raw/main/environment.yml
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/geocompr/py/main/environment.yml [following]
--2022-08-25 17:38:43--  https://raw.githubusercontent.com/geocompr/py/main/environment.yml
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 351 [text/plain]
Saving to: ‘environment.yml’

     0K                                                       100% 15.9M=0s

2022-08-25 17:38:44 (15.9 MB/s) - ‘environment.yml’ saved [351/351]

Removing intermediate container fb80020bc128
 ---> 8cc3096e5f34
Step 3/6 : RUN conda env create -f environment.yml
 ---> Running in 8eecb51d24c2
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... Killed
Removing intermediate container 8eecb51d24c2
The command '/bin/sh -c conda env create -f environment.yml' returned a non-zero code: 137Built image, launching...
Failed to connect to event stream
```

**Comment by michaeldorman** [comment]
Sorry, no idea what this means...

**Comment by anisotropi4** [comment]
```
Removing intermediate container fb80020bc128 ---> 8cc3096e5f34
Step 3/6 : RUN conda env create -f environment.yml ---> Running in 8eecb51d24c2
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... Killed
```

Suggests to me a system resource issue causing the process to fail.

**Comment by Robinlovelace** [comment]
It's a strange one... I guess adding a .binder folder with config files in there could solve it, e.g. from the R version: https://github.com/Robinlovelace/geocompr/tree/main/.binder

Could the fact that the .ipynb files are in a separate folder be part of the issue?

**Comment by Robinlovelace** [comment]
final thought on this, would be very cool to have the VS Code editor enabled: https://github.com/betatim/vscode-binder

**Comment by anitagraser** [comment]
> Could the fact that the .ipynb files are in a separate folder be part of the issue?

I doubt it. In https://github.com/anitagraser/movingpandas-examples the notebooks are also in a separate folder

**Comment by Robinlovelace** [comment]
Next step on this: @Nowosad to try removing dependencies from environment.yml and see which ones cause the fail. If not we can ask online..

**Comment by Nowosad** [comment]
@Robinlovelace I tried to fix it for some time already, sadly without any success. My current thinking is to wait for work on https://github.com/geocompr/py/issues/87 and then use the docker image (the same as in https://github.com/Robinlovelace/geocompr/tree/main/.binder).

**Comment by Robinlovelace** [comment]
@Nowosad did you try unpinning the Python version?

**Comment by Robinlovelace** [comment]
Looking at another environment.yml file, it seems that line can simply be removed: https://github.com/geopandas/geopandas/blob/main/environment.yml

**Comment by Robinlovelace** [comment]
Getting these messages on load: 

```
Waiting for build to start...
Picked Git content provider.
Cloning into '/tmp/repo2dockerolfl3cxp'...
HEAD is now at 9f7d58a Unpin Python version (#84)
Using DockerBuildPack builder
Step 1/6 : FROM continuumio/miniconda3
 ---> ce7d119281a1
Step 2/6 : RUN wget https://github.com/geocompr/py/raw/main/environment.yml
 ---> Using cache
 ---> 3089a68bb62a
Step 3/6 : RUN conda env create -f environment.yml
 ---> Using cache
 ---> 00d1154ba1f2
Step 4/6 : LABEL repo2docker.ref=9f7d58a6b4538c5cc7e69e93e206317a86119359
 ---> [Warning] Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
 ---> Running in b6fcdc4c3643
Removing intermediate container b6fcdc4c3643
 ---> bb22f3110f61
Step 5/6 : LABEL repo2docker.repo=https://github.com/geocompr/py
 ---> [Warning] Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
 ---> Running in 59eb5414fde4
Removing intermediate container 59eb5414fde4
 ---> 10795c970f6c
Step 6/6 : LABEL repo2docker.version=2022.02.0+90.g0345a86
 ---> [Warning] Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
 ---> Running in a965a9e8f9fe
Removing intermediate container a965a9e8f9fe
 ---> bdb21893cbf7
{"aux": {"ID": "sha256:bdb21893cbf7e0a1eda45d654782143fc8ac8c5a37bd397ba6aece6f188b59d7"}}[Warning] One or more build-args [NB_USER NB_UID] were not consumed
Successfully built bdb21893cbf7
Successfully tagged turingmybinder/binder-prod-r2d-g5b5b759-geocompr-2dpy-411c8d:9f7d58a6b4538c5cc7e69e93e206317a86119359
Pushing image
Successfully pushed turingmybinder/binder-prod-r2d-g5b5b759-geocompr-2dpy-411c8d:9f7d58a6b4538c5cc7e69e93e206317a86119359Built image, launching...
Launching server...
Server requested
2022-09-28T18:36:01.356060Z [Normal] Successfully assigned turing/jupyter-geocompr-2dpy-2ddhtxet2k to aks-user-15162993-vmss000001
2022-09-28T18:36:02Z [Normal] Container image "jupyterhub/mybinder.org-tc-init:2020.12.4-0.dev.git.4289.h140cef5" already present on machine
2022-09-28T18:36:02Z [Normal] Created container tc-init
2022-09-28T18:36:02Z [Normal] Started container tc-init
2022-09-28T18:36:03Z [Normal] Pulling image "turingmybinder/binder-prod-r2d-g5b5b759-geocompr-2dpy-411c8d:9f7d58a6b4538c5cc7e69e93e206317a86119359"
2022-09-28T18:36:12Z [Normal] Successfully pulled image "turingmybinder/binder-prod-r2d-g5b5b759-geocompr-2dpy-411c8d:9f7d58a6b4538c5cc7e69e93e206317a86119359" in 9.756206476s
2022-09-28T18:36:12Z [Normal] Created container notebook
2022-09-28T18:36:12Z [Normal] Started container notebook
Spawn failed: Server at http://10.244.1.67:8888/user/geocompr-py-dhtxet2k/ didn't respond in 30 seconds
Launch attempt 1 failed, retrying...
Server requested
2022-09-28T18:36:52.292846Z [Normal] Successfully assigned turing/jupyter-geocompr-2dpy-2d90ag2axf to aks-user-15162993-vmss000001
2022-09-28T18:36:52Z [Normal] Container image "jupyterhub/mybinder.org-tc-init:2020.12.4-0.dev.git.4289.h140cef5" already present on machine
2022-09-28T18:36:53Z [Normal] Created container tc-init
2022-09-28T18:36:53Z [Normal] Started container tc-init
2022-09-28T18:36:53Z [Normal] Container image "turingmybinder/binder-prod-r2d-g5b5b759-geocompr-2dpy-411c8d:9f7d58a6b4538c5cc7e69e93e206317a86119359" already present on machine
2022-09-28T18:36:53Z [Normal] Created container notebook
2022-09-28T18:36:53Z [Normal] Started container notebook
```

Anyone know of those are normal?

Source: https://mybinder.org/v2/gh/geocompr/py/main?urlpath=lab/tree/ipynb

**Comment by Robinlovelace** [comment]
Another option: codespaces.

![image](https://user-images.githubusercontent.com/1825120/192899699-1910fd75-9d1b-4f5e-8568-656fad1560f6.png)

Source: [![Open in GitHub Codespaces](https://github.com/codespaces/badge.svg)](https://github.com/codespaces/new?hide_repo_select=true&ref=main&repo=447558863)

**Comment by Robinlovelace** [comment]
Another option: codespaces.

![image](https://user-images.githubusercontent.com/1825120/192899699-1910fd75-9d1b-4f5e-8568-656fad1560f6.png)

Source: [![Open in GitHub Codespaces](https://github.com/codespaces/badge.svg)](https://github.com/codespaces/new?hide_repo_select=true&ref=main&repo=447558863)

**Comment by Nowosad** [comment]
Hi @Robinlovelace -- yes, I tried to unpin the Python version (and many more thing). All of my tries resulted in a few different mybinder errors. Thus, I would suggest using mybinder based on our docker image, instead of enviroment.yml file.

**Comment by Robinlovelace** [comment]
> I would suggest using mybinder based on our docker image

Yes that's a logical next step. Are you happy to give that a go? FYI recent experiments building on `geocompr/geocompr:conda` image have been pretty successful and the devcontainer.json file seems to work, but the codespaces, GitPod and binder approaches are pretty different, worth trying all of them for redundancy.

**Comment by Nowosad** [comment]
@Robinlovelace please try the binder now.

**Comment by Robinlovelace** [comment]
Taking a look :eyes: @Nowosad

**Comment by Robinlovelace** [comment]
Progress but no cigar... 
![image](https://user-images.githubusercontent.com/1825120/193472920-2f4fcd05-32aa-4f42-a968-65feb406252f.png)

I guess we need to activate the `geocompy` env on the image. I would love to have an environment-free Docker image that would 'just work' without worrying about changing environments but that seems tricky https://github.com/geocompr/py/pull/90 - would love to get it working and I believe @michaeldorman has the packages installed using pip alone, just not in a Docker container yet. I tried many times to build the image starting from a fresh Ubuntu 22.04 instance in https://github.com/geocompr/py/pull/90, if we could get that working that would be great.

**Comment by michaeldorman** [comment]
Yes, I'm still using just `pip` and no environments... Just installing with `pip install ...`. Surprisingly it worked well so far :-)

**Comment by Robinlovelace** [comment]
FYI this is what I tried in the docker-test branch, would be good to identify which packages/versions caused the fail: https://github.com/geocompr/py/pull/91/files

**Comment by Robinlovelace** [comment]
With

```
pip install -r requirements.txt
```

If I remember correctly.

**Comment by michaeldorman** [comment]
I'd try to re-install the minimal set of packages from scratch with: 

```sh
pip install geopandas
pip install rasterio
# etc.
```

and then recreate the `requirements.txt` file after making sure that all book codes work:

```sh
pip freeze > requirements.txt
```

Don't see another way to detect which packages and versions are incompatible in the existing file...

**Comment by Robinlovelace** [comment]
> Don't see another way to detect which packages and versions are incompatible in the existing file...

Trial and error in a Docker container, starting with the core packages and adding more exotic / less used ones one-by-one is my thinking on approach. I think the requirements.txt file can be unpinned, right? After it's in a Docker container that 'freezes' them until the next time we successfully rebuild the image.

**Comment by Nowosad** [comment]
We are not suggesting to use Binder in README. Reopen if needed.
