### ISSUE TITLE
Output format of some figures

### ISSUE THREAD

**Issue by Nowosad** [geocompx/geocompy#97]
I've been making some progress on the PDF version of the book. There are some small obstacles (i.e., I think I know how to fix them), and one problem I do not know how to fix:

The `plot()` method and ` show()` function return PNG files (e.g., [cell-9-output-1.png](https://geocompr.github.io/py/02-spatial-data_files/figure-html/cell-9-output-1.png)) -- that's good (and easy to change). However,  **shapely** objects are printed as SVG files (e.g., [cell-17-output-1.svg](https://geocompr.github.io/py/02-spatial-data_files/figure-html/cell-17-output-1.svg)) -- see https://geocompr.github.io/py/02-spatial-data.html#geometries. 

The question is: how can we force these figures to be in the PNG (or some other than SVG) format?

**Comment by anitagraser** [comment]
Sorry, I'm not aware of a solution for the shapely SVGs. If I find something, I'll let you know.

**Comment by Nowosad** [comment]
Related issue: https://github.com/quarto-dev/quarto-cli/issues/997

**Comment by Robinlovelace** [comment]
> The question is: how can we force these figures to be in the PNG (or some other than SVG) format?

I guess something like this could help: https://cairosvg.org/

**Comment by michaeldorman** [comment]
Well, last resort could be to:
1. Run `quarto render` and let it fail, but it produces the `tex` file and `svg` files
2. Convert all `svg` files to `pdf`, using @Robinlovelace suggestion or other tools such as Inkscape
3. Replace all occurrences of `.svg` with `.pdf` in the `tex` file
4. Run `pdflatex book.tex`

Worked with this small example:

```text
---
title: "My document"
format:
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
---

## Setup

```{python}
import shapely
```

```{python}
polygon = shapely.geometry.Polygon([(1,5), (2,2), (4,1), (4,4), (1,5)], [[(2,4), (3,4), (3,3), (2,3), (2,4)]])
polygon
```

Result:
![Screenshot from 2022-10-02 23-56-28](https://user-images.githubusercontent.com/9386655/193475999-e3fb423f-8959-45c2-bbd1-79dca330f3d8.png)


I can write a script to do that, unless we find a more elegant solution.

**Comment by michaeldorman** [comment]
P.S. Didn't find a way for `shapely` to produce PNG instead of SVG yet...

**Comment by Robinlovelace** [comment]
Sounds like a good plan Michael, as long as it's automated, no problem. I'm surprised shapely cannot export .png files, imagine someone has already asked on their issue tracker/elsewhere and it's a 'wontfix' or 'long time away' upstream issue.

**Comment by Nowosad** [comment]
Great @michaeldorman. This can be our failback. My current thinking is just to wait for this conversion to be fixed in quarto -- https://github.com/quarto-dev/quarto-cli/issues/2575. We can revise this issue in a few months.

**Comment by Nowosad** [comment]
Works now.
