### ISSUE TITLE
Figure of GeoDataFrame structure

### ISSUE THREAD

**Issue by michaeldorman** [geocompx/geocompy#98]
To prepare a figure such as https://geocompr.robinlovelace.net/spatial-class.html#fig:02-sfdiagram about the relation between shapely, Series/GeoSeries, and GeoDataFrame

**Comment by Nowosad** [comment]
@michaeldorman if you can draw a draft of it by hand (or some basic viz software) and share the picture, I can prepare such figure.

**Comment by michaeldorman** [comment]
Please see here:
https://github.com/geocompx/py/pull/139/commits/11eafd407822e87a0f1196ca82bb623da493a73a

**Comment by michaeldorman** [comment]
![Screenshot from 2022-12-24 00-26-35](https://user-images.githubusercontent.com/9386655/209410518-ed1f1995-ebbf-4501-a4b5-fab3c3550f18.png)
